FactoryGirl.define do
  factory :monster do
    family 'Chimera'
    name 'Chimera'
    altname 'None'
    size 'Large'
    genre 'Magical Beast'
    descriptor 'None'
    hit_dice '9d10+27 (76 hp)'
    initiative '+1'
    speed '30 ft. (6 squares), fly 50 ft. (poor)'
    armor_class '19 (-1 size, +1 Dex, +9 natural), touch 10, flat-footed 18'
    base_attack '+9'
    grapple '+17'
    attack 'Bite +12 melee (2d6+4)'
    full_attack 'Bite +12 melee (2d6+4) and bite +12 melee (1d8+4) and gore +12 melee (1d8+4) and 2 claws +10 melee (1d6+2)'
    space '10 ft.'
    reach '5 ft.'
    special_attacks 'Breath weapon'
    special_qualities 'Darkvision 60 ft., low-light vision, scent'
    saves 'Fort +9, Ref +7, Will +6'
    abilities 'Str 19, Dex 13, Con 17, Int 4, Wis 13, Cha 10'
    skills 'Hide +1*, Listen +9, Spot +9'
    bonus_feats 'None'
    feats 'Alertness, Hover, Iron Will, Multiattack'
    epic_feats 'None'
    environment 'Temperate hills'
    organization 'Solitary, pride (3-5), or flight (6-13)'
    challenge_rating '7'
    treasure 'Standard'
    alignment 'Usually chaotic evil'
    advancement '10-13 HD (Large); 14-27 HD (Huge)'
    level_adjustment '+2 (cohort)'
    special_abilities 'Breath Weapon (Su)'
    stat_block 'Chimera; CR 7; Large magical beast; HD 9d10+27; hp 76; Init +1; Spd 30 ft. (6 squares), fly 50 ft. (poor); AC 19 (-1 size, +1 dex, +9 natural), touch 10, flat-footed 18; Base Atk +9; Grp +17; Atk +12 melee (2d6+4, bite); Full Atk +12 melee (2d6+4, bite) and +12 melee (1d8+4, bite) and +12 melee (1d8+4, gore) and +10 melee (1d6+2, 2 claws); Space/Reach 10 ft./5 ft.; SA Breath weapon; SQ Darkvision 60 ft., low-light vision, scent; AL CE; SV Fort +9, Ref +7, Will +6; Str 19, Dex 13, Con 17, Int 4, Wis 13, Cha 10, Skills and Feats: Hide +1*, Listen +9, Spot +9; Alertness, Hover, Iron Will, Multiattack'
    full_text 'Killer Beast'
    reference 'SRD 3.5 MonstersB-C'
  end
end
